### ISSUE TITLE
4. Quiz Logica

### ISSUE THREAD

**Issue by EllenVstb** [natiapreutesei/teamproject#4]
Programmeren van de quizlogica in JavaScript.
Verifiëren van de ingevoerde landnaam en het tonen van de juiste/foute icoontjes

**Comment by natiapreutesei** [comment]
Ollivie - program the quiz logic. 
_(Implementation with code Nathan)_
After the cards are generated you will have on screen (depending on the input of the user) 5 cards.
Those 5 cards look like this: 
```
IMAGE FLAG
INPUT field - this is where the user will write the name of that country. 
Check button - the button that call the function to check if choice is correct.
```

Then it injects code into the HTML with a green tick if correct and red if incorrect.  - (needs to be implemented when Ellen has finished her code)


Ellen  - program the scoreboard functionality. 
_(Implementation with code Ollivie and Nathan)_
First, it takes the value of the number of cards that were generated. That's the total amount for the score. (Example ..../14 [random number by the user] )
This program takes from Ollivie program and checks if the choice is correct. 
If it was correct it adds one to a variable. It does this for all of the correct choices. 
Then it displays the score. (Here we can choose when it displays the score but I guess the easier implementation is for it to go up at the same time as the user chooses. Otherwise it could be difficult to tell the code to wait until all the flags have been checked and the to show the result. _we need to talk about this_ )
